# Generated by Django 3.0.3 on 2022-04-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('did', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100)),
                ('demail', models.EmailField(max_length=254)),
                ('dpass', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'doctors',
            },
        ),
    ]
